# Numerical tools

## Objectives
* Learn how to use numpy's arrays
* Learn how to maninipulate arrays without loops
* Learn about broadcasting

## Numpy

Numpy is the most important numerical library available for Python. Several pieces of Python syntax were added explicitly to support Numpy, such as the Ellipsis and the matrix multiplication operator.

The most common way to import numpy is as follows:

In [1]:
import numpy as np

### Arrays

The numpy library is build around the array. Arrays are different from Python lists:
* Arrays can be multidimensional, and have a `.shape`
* Arrays hold a specific `dtype` only
* Arrays cannot change size (but can change shape)
* Operations are element-wise

> If you have used Matlab before, note that arrays in Python support 0 and 1 dimensions besides the normal 2+, and that operations are elementwise.

In [19]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [20]:
arr.shape

(4,)

In [21]:
arr.dtype

dtype('int64')

Operations on an array are defined as elementwise (with the exceptions of the logic operators - numpy uses bitwise operators instead).

In [22]:
arr ** 2

array([ 1,  4,  9, 16])

In [38]:
(arr == 1) | (arr == 2)

array([ True,  True, False, False])

### Creating arrays

You can produce new arrays many different ways:

In [ ]:
np.zeros(3)

In [ ]:
np.zeros(3, dtype=np.int8)

In [ ]:
np.ones([2,2])

In [ ]:
np.eye(3)

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randint(2,5,(3,4))

### Ufuncs

Numpy also provides UFuncs; functions that apply element-wise to an array. They do so without a Python loop, making them very fast. There are also a collection of other useful functions that do things like `sum` without Python loops.

> Technically, UFuncs must produce the same size output array. Ones that produce different output array sizes are called Generalized UFuncs, but that distinction will not matter to us for now.

In [ ]:
np.sin(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.sum(arr)

## Reshaping

We can take an array and reshape it:

In [ ]:
a = np.eye(4)
a

In [ ]:
a.reshape(2,8)

In [ ]:
a.reshape(2,-1)

In [ ]:
a.reshape(1,16)

In [ ]:
a.reshape(16)

In [ ]:
a.flatten()

We can also add new empty axis:

In [ ]:
b = np.array([1,2,3])
b[:,np.newaxis]

In [ ]:
b[np.newaxis,:]

## Data types

* int: 8 (char), 16 (short), 32 (int), 64 (long) bits - optionally unsigned
* float: 16 (half), 32 (float), 64 (double) bits
* bool: Generally 8 bits for performance reasons

In [ ]:
np.uint8(1)

In [ ]:
np.float16(12.123456789123456789123456789)