# Numerical tools

## Objectives
* Learn about importing libraries
* Learn how to use numpy

Python has the idea of libraries that can be imported. It has a large standard library of modules you have access to, and many more in the Python Package Index (PyPI). For now, we'll only talk about libraries in the standard library or in the list of libraries included in Anaconda.

To import functionality from a library:

In [1]:
import math
print(math.sqrt)

<built-in function sqrt>


In [2]:
import math as m
print(m.sqrt)

<built-in function sqrt>


In [3]:
from math import sqrt
print(sqrt)

<built-in function sqrt>


You can also use `from math import *`, but this is usually a bad idea, since you no longer know where things come from.

It is safe to import a module multiple times; once imported, Python will use the already imported copy instead of re-importing it.

## Numpy

Numpy is the most important numerical library available for Python. Several pieces of Python syntax were added explicitly to support Numpy, such as the Ellipsis and the matrix multiplication operator.

The most common way to import numpy is as follows:

In [1]:
import numpy as np

### Arrays

The numpy library is build around the array. Arrays are different from Python lists:
* Arrays can be multidimensional, and have a `.shape`
* Arrays hold a specific `dtype` only
* Arrays cannot change size (but can change shape)
* Operations are element-wise

> If you have used Matlab before, note that arrays in python support 0 and 1 dimensions, and that operations are elementwise.

In [7]:
arr = np.array([1,2,3,4])

In [6]:
arr.shape

(4,)

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr ** 2

array([ 1,  4,  9, 16])

### Creating arrays

You can produce new arrays many different ways:

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros(3, dtype=np.int8)

array([0, 0, 0], dtype=int8)

In [16]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(2,2)

array([[0.25882216, 0.17274469],
       [0.92075354, 0.69528851]])

In [25]:
np.random.randint(2,5,(3,4))

array([[2, 4, 2, 2],
       [3, 3, 2, 3],
       [4, 2, 4, 3]])

### Ufuncs

Numpy also provides UFuncts; functions that apply element-wise to an array. They do so without a Python loop, making them very fast. There are also a collection of other useful functions that do things like `sum` without Python loops.

> Technically, UFuncts produce the same size output array. Ones that produce different output array sizes are called Generalized UFuncts, but that distinction will not matter to us for now.

In [10]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [11]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [12]:
np.sum(arr)

10

## Reshaping

We can take an array and reshape it:

In [29]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
a.reshape(2,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [33]:
a.reshape(2,-1)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [36]:
a.reshape(1,16)

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [34]:
a.reshape(16)

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [35]:
a.flatten()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

We can also add new empty axis:

In [37]:
b = np.array([1,2,3])
b[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [38]:
b[np.newaxis,:]

array([[1, 2, 3]])

## Data types

* int: 8 (char), 16 (short), 32 (int), 64 (long) bits - optionally unsigned
* float: 16 (half), 32 (float), 64 (double) bits
* bool: Generally 8 bits for performance reasons

In [6]:
np.uint8(1)

1

In [16]:
np.float16(12.123456789123456789123456789)

12.125